print ("Olá, eu sou a Siri. Agora, tenho IA e serei seu chatbot em todo o ecossistema Apple. Eu sou movido pela Apple Intelligence. Isto será uma demonstração de como funciono agora.")
print ("Feito pela Apple na Califórnia")
nome=input("Qual o teu nome? ")
print ("Olá "+nome+". Podes testar-me perguntando-me:")
pergunta=input("Qual o meu modelo? Pergunta.")
print("Eu sou alimentado pelo Apple Intelligence desenvolvido pela Apple e movido em certas funcionalidades pelo GPT-4o da OpenAI e que tem muitas capacidades. Comigo, podes-me perguntar-me qualquer coisa normalmente pela voz sem stress.")
despedida=input("Está na hora da despedida.")
print("Obrigado "+nome+". Adeus.")
